name: fynix
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  provider: ^6.1.5+1
  http: ^1.5.0
  supabase_flutter: ^2.10.3
  google_sign_in: ^7.2.0
  localstore: ^1.4.0
  connectivity_plus: ^7.0.0
  uuid: ^4.5.2

  intl: ^0.18.1
  fl_chart: ^0.70.0
  shared_preferences: ^2.5.3
  pdf: ^3.10.4
  printing: ^5.11.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/waves/

platforms:
  linux:
  macos:
  windows:
  android:
  ios:
  web:
